In [1]:
import numpy as np


In [4]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
print(f"Array mat1D : {mat1D}")
print(f"Array mat1D + 10 {mat1D + 10}")
print(f"Array mat1D indeks ke 2 : {mat1D [2]}")

Array mat1D : [1 2 3 4 5 6 7 8 9]
Array mat1D + 10 [11 12 13 14 15 16 17 18 19]
Array mat1D indeks ke 2 : 3


In [11]:
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Array mat2D : {mat2D}")
print(f"Array mat2D + 10 {mat2D + 10}")

Array mat2D : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array mat2D + 10 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [13]:
print(mat1D.shape) #mengetahui bentuk matriks
print(mat2D.shape)

(9,)
(3, 3)


In [14]:
print(mat1D.size) #mengetahui ukuran dari matriks
print(mat2D.size)

9
9


In [25]:
#special matriks
mZero = np.zeros((3,3))
mOne = np.ones((4,4))
mIdentity = np.eye((4))
mFull = np.full((3,3),10)

print(f"Matriks mZero : \n {mZero}")
print(f"Matriks mOne : \n {mOne}")
print(f"Matriks identity : \n {mIdentity}")
print(f"Matriks mFull : \n {mFull}")


Matriks mZero : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriks mOne : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriks identity : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriks mFull : 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [28]:
#Aritmatic Array
x = np.array([2,3,4])
y = np.array([5,5,5])
r1 = np.dot(x,y) #
r2 = np.add(x,y) #penjumlahan matriks dimana ordonya harus sama
print(f"r1 : {r1}")
print(f"r2 : {r2}")

r1 : 45
r2 : [7 8 9]


In [36]:
nilaiPemrograman = np.array([100,90,80,70,60,50,40])
nMin = np.min(nilaiPemrograman)
nMax = np.max(nilaiPemrograman)
nMean = np.mean(nilaiPemrograman)
nSum = np.sum(nilaiPemrograman)
nMedian = np.median(nilaiPemrograman)
nStd = np.std(nilaiPemrograman)

print(nilaiPemrograman)
print(f"nMin : {nMin}")
print(f"nMax : {nMax}")
print(f"nMean : {nMean}")
print(f"nSum : {nSum}")
print(f"nMedian : {nMedian}")
print(f"Nilai Deviasi : {nStd}")

[100  90  80  70  60  50  40]
nMin : 40
nMax : 100
nMean : 70.0
nSum : 490
nMedian : 70.0
Nilai Deviasi : 20.0
